config setup

conn transit-r1-1-r3-2
    type=transport
    authby=secret
    left=10.31.0.2
    right=10.31.0.1
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    keyingtries=%forever
    auto=start
    dpddelay=10s
    dpdtimeout=30s
    dpdaction=restart

