frr version 10.7
frr defaults traditional
hostname r3-2
log syslog informational
no ipv6 forwarding
!
interface lo
 ip address 10.0.3.2/32
!
interface eth1
 ip address 10.3.0.2/24
!
interface eth2
 ip address 10.31.0.1/30
!
router ospf
 network 10.0.3.2/32 area 0
 network 10.3.0.0/24 area 0
!
router bgp 65003
 no bgp ebgp-requires-policy
 bgp router-id 10.0.3.2
 neighbor 10.0.3.1 remote-as 65003
 neighbor 10.0.3.1 update-source lo
 neighbor 10.0.3.1 next-hop-self
 neighbor 10.31.0.2 remote-as 65001
 !
 address-family ipv4 unicast
  network 10.0.3.2/32
  neighbor 10.0.3.1 activate
  neighbor 10.31.0.2 activate
 exit-address-family
!
line vty
!

