frr version 10.7.0_git
frr defaults traditional
hostname r2-2
!
vrf red
exit-vrf
!
vrf blue
exit-vrf
!
interface dummy-red vrf red
 ip address 172.16.22.1/32
exit
!
interface dummy-blue vrf blue
 ip address 172.17.22.1/32
exit
!
interface eth1
 ip address 10.2.0.2/24
exit
!
interface eth2
 ip address 10.23.0.1/30
exit
!
interface lo
 ip address 10.0.2.2/32
exit
!
router bgp 65002
 bgp router-id 10.0.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.2.1 remote-as 65002
 neighbor 10.0.2.1 update-source lo
 neighbor 10.23.0.2 remote-as 65003
 !
 address-family ipv4 unicast
  network 10.0.2.2/32
  neighbor 10.0.2.1 next-hop-self
 exit-address-family
 !
 address-family ipv4 vpn
  neighbor 10.0.2.1 activate
  neighbor 10.23.0.2 activate
 exit-address-family
exit
!
router bgp 65002 vrf red
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65002:102
  rt vpn both 65000:100
  export vpn
  import vpn
 exit-address-family
exit
!
router bgp 65002 vrf blue
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65002:202
  rt vpn both 65000:200
  export vpn
  import vpn
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.2.2
 network 10.0.2.2/32 area 0
 network 10.2.0.0/24 area 0
 mpls ldp-sync
exit
!
mpls ldp
 router-id 10.0.2.2
 !
 address-family ipv4
  discovery transport-address 10.0.2.2
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
