frr version 10.7.0_git
frr defaults traditional
hostname r1-2
!
vrf red
exit-vrf
!
vrf blue
exit-vrf
!
interface dummy-red vrf red
 ip address 172.16.12.1/32
exit
!
interface dummy-blue vrf blue
 ip address 172.17.12.1/32
exit
!
interface eth1
 ip address 10.1.0.2/24
exit
!
interface eth2
 ip address 10.12.0.1/30
exit
!
interface lo
 ip address 10.0.1.2/32
exit
!
router bgp 65001
 bgp router-id 10.0.1.2
 no bgp ebgp-requires-policy
 neighbor 10.0.1.1 remote-as 65001
 neighbor 10.0.1.1 update-source lo
 neighbor 10.12.0.2 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.0.1.2/32
  neighbor 10.0.1.1 next-hop-self
 exit-address-family
 !
 address-family ipv4 vpn
  neighbor 10.0.1.1 activate
  neighbor 10.0.1.1 next-hop-self
  neighbor 10.12.0.2 activate
 exit-address-family
exit
!
router bgp 65001 vrf red
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65001:102
  rt vpn both 65000:100
  export vpn
  import vpn
 exit-address-family
exit
!
router bgp 65001 vrf blue
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65001:202
  rt vpn both 65000:200
  export vpn
  import vpn
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.1.2
 network 10.0.1.2/32 area 0
 network 10.1.0.0/24 area 0
 network 10.12.0.0/30 area 0
 mpls ldp-sync
exit
!
mpls ldp
 router-id 10.0.1.2
 !
 address-family ipv4
  discovery transport-address 10.0.1.2
  !
  interface eth1
  exit
  !
  interface eth2
  exit
  !
 exit-address-family
 !
exit
!
