config setup
    charondebug="ike 2, knl 2, cfg 2"

conn r2-2-to-r3-1
    type=transport
    authby=secret
    left=10.23.0.1
    right=10.23.0.2
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    auto=start
    keyingtries=%forever
    dpddelay=10
    dpdtimeout=30
    dpdaction=restart
