config setup
    charondebug="ike 2, knl 2, cfg 2"

conn r2-1-to-r1-2
    type=transport
    authby=secret
    left=10.12.0.2
    right=10.12.0.1
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    auto=start
    keyingtries=%forever
    dpddelay=10
    dpdtimeout=30
    dpdaction=restart
