config setup

conn transit-r3-1-r2-2
    type=transport
    authby=secret
    left=10.23.0.2
    right=10.23.0.1
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    keyingtries=%forever
    auto=start
    dpddelay=10s
    dpdtimeout=30s
    dpdaction=restart

