frr version 10.7
frr defaults traditional
hostname r2-1
log syslog informational
no ipv6 forwarding
!
interface lo
 ip address 10.0.2.1/32
!
interface eth1
 ip address 10.2.0.1/24
!
interface eth2
 ip address 10.12.0.2/30
!
router ospf
 network 10.0.2.1/32 area 0
 network 10.2.0.0/24 area 0
!
router bgp 65002
 no bgp ebgp-requires-policy
 bgp router-id 10.0.2.1
 neighbor 10.0.2.2 remote-as 65002
 neighbor 10.0.2.2 update-source lo
 neighbor 10.0.2.2 next-hop-self
 neighbor 10.12.0.1 remote-as 65001
 !
 address-family ipv4 unicast
  network 10.0.2.1/32
  neighbor 10.0.2.2 activate
  neighbor 10.12.0.1 activate
 exit-address-family
!
line vty
!

